name: haskell-verify-examples
synopsis: Verify examples in your docs.
description: Please see the README at <https://github.com/NoRedInk/haskell-verify-examples/tree/trunk/#readme>.
author: NoRedInk
version: 0.0.0.1
maintainer: haskell-open-source@noredink.com
copyright: 2021 NoRedInk Corp.
github: NoRedInk/haskell-verify-examples
license-file: LICENSE
category: Web
extra-source-files:
  - README.md
  - LICENSE
data-files:
  - src/Haskell/Verify/Examples/RunTime.hs
  - src/Haskell/Verify/Examples/Verified.hs
executables:
  haskell-verify-examples:
    dependencies:
      - conduit >= 1.3.4.1 && < 1.4
      - filemanip >= 0.3.6.3 && < 0.3.7
      - optparse-applicative >= 0.16.1.0 && < 0.17
      - async >= 2.2.2 && < 2.3
      - base >= 4.12.0.0 && < 4.16
      - bytestring >= 0.10 && < 0.11
      - cpphs >= 1.20.9.1 && < 1.21
      - directory >= 1.3.6.0 && < 1.4
      - filepath >= 1.4 && < 1.5
      - haskell-src-exts >= 1.23.1 && < 1.24
      - hie-bios >= 0.7.5 && < 0.8
      - hint >= 0.9.0.4 && < 0.10
      - junit-xml >= 0.1.0.2 && < 0.2
      - nri-prelude >= 0.1.0.0 && < 0.7
      - pretty-diff >= 0.4.0.2 && < 0.5
      - pretty-show >= 1.9.5 && < 1.11
      - safe-coloured-text >= 0.0.0.0 && < 0.1
      - safe-exceptions >= 0.1.7 && < 0.1.8
      - temporary >= 1.3 && < 1.4
      - terminal-size >= 0.3.2.1 && < 0.4
      - text >= 1.2.3.1 && < 1.3
    main: Main.hs
    source-dirs: 
      - app
      - src
  generate-documentation:
    dependencies:
      - conduit >= 1.3.4.1 && < 1.4
      - async >= 2.2.2 && < 2.3
      - base >= 4.12.0.0 && < 4.16
      - bytestring >= 0.10 && < 0.11
      - cpphs >= 1.20.9.1 && < 1.21
      - directory >= 1.3.6.0 && < 1.4
      - filepath >= 1.4 && < 1.5
      - haskell-src-exts >= 1.23.1 && < 1.24
      - hie-bios >= 0.7.5 && < 0.8
      - hint >= 0.9.0.4 && < 0.10
      - junit-xml >= 0.1.0.2 && < 0.2
      - nri-prelude >= 0.1.0.0 && < 0.7
      - pretty-diff >= 0.4.0.2 && < 0.5
      - pretty-show >= 1.9.5 && < 1.11
      - safe-coloured-text >= 0.0.0.0 && < 0.1
      - safe-exceptions >= 0.1.7 && < 0.1.8
      - temporary >= 1.3 && < 1.4
      - terminal-size >= 0.3.2.1 && < 0.4
      - text >= 1.2.3.1 && < 1.3
    main: Main.hs
    source-dirs: 
      - doc
      - src
library:
  dependencies:
  - conduit >= 1.3.4.1 && < 1.4
  - async >= 2.2.2 && < 2.3
  - base >= 4.12.0.0 && < 4.16
  - bytestring >= 0.10 && < 0.11
  - cpphs >= 1.20.9.1 && < 1.21
  - directory >= 1.3.6.0 && < 1.4
  - filepath >= 1.4 && < 1.5
  - haskell-src-exts >= 1.23.1 && < 1.24
  - hie-bios >= 0.7.5 && < 0.8
  - hint >= 0.9.0.4 && < 0.10
  - junit-xml >= 0.1.0.2 && < 0.2
  - nri-prelude >= 0.1.0.0 && < 0.7
  - pretty-diff >= 0.4.0.2 && < 0.5
  - pretty-show >= 1.9.5 && < 1.11
  - safe-coloured-text >= 0.0.0.0 && < 0.1
  - safe-exceptions >= 0.1.7 && < 0.1.8
  - temporary >= 1.3 && < 1.4
  - terminal-size >= 0.3.2.1 && < 0.4
  - text >= 1.2.3.1 && < 1.3
  exposed-modules:
  - Haskell.Verify.Examples
  - Haskell.Verify.Examples.RunTime
  - Haskell.Verify.Examples.Verified
  source-dirs: src
tests:
  spec:
    dependencies:
    - conduit >= 1.3.4.1 && < 1.4
    - aeson >= 1.4.6.0 && < 1.6
    - async >= 2.2.2 && < 2.3
    - base >= 4.12.0.0 && < 4.16
    - bytestring >= 0.10 && < 0.11
    - cpphs >= 1.20.9.1 && < 1.21
    - directory >= 1.3.6.0 && < 1.4
    - filepath >= 1.4 && < 1.5
    - haskell-src-exts >= 1.23.1 && < 1.24
    - hie-bios >= 0.7.5 && < 0.8
    - hint >= 0.9.0.4 && < 0.10
    - junit-xml >= 0.1.0.2 && < 0.2
    - nri-prelude >= 0.1.0.0 && < 0.7
    - pretty-diff >= 0.4.0.2 && < 0.5
    - pretty-show >= 1.9.5 && < 1.11
    - safe-coloured-text >= 0.0.0.0 && < 0.1
    - safe-exceptions >= 0.1.7 && < 0.1.8
    - temporary >= 1.3 && < 1.4
    - terminal-size >= 0.3.2.1 && < 0.4
    - text >= 1.2.3.1 && < 1.3
    main: Main.hs
    source-dirs:
    - src
    - test
    # We intentionally do not add threaded ghc-options for tests. These would
    # cause tests to run in parallel, which introduces flakiness in this test
    # suite. The suite creates a number of web servers that are supposed to get
    # unique ports, but if we start them in parallel this will not always work.
    ghc-options:
      - -fno-warn-type-defaults
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - ScopedTypeVariables
  - Strict
  - TypeOperators
  - ExtendedDefaultRules
  - NumericUnderscores
ghc-options:
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
  - -fplugin=NriPrelude.Plugin
