name: Makefile CI

on:
  push:
    branches:
      - trunk

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v14
      
    - name: Run check
      run: nix-shell --run "make check"

    - name: Cache stuff
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
          /nix/store/
        key: ${{ runner.os }}-${{ matrix.ghc }}
